name: Application Deployment Testing Pipeline

on: 
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node Js
        uses:  actions/setup-node@v4
        with:
          node-version: 25
          cache: "npm"
      
      - name: Install Dependencies
        run: npm ci

      - name: Dependencies Scanning
        run: npm audit --audit-level=high

      - name: Building React Application
        run: npm run build

      - name: Final Message
        run: echo Code Tested Successfully
     